module.exports = {
	printWidth: 80,
	tabWidth: 4,
	useTabs: true,
	singleQuote: true,
	quoteProps: 'consistent',
	jsxSingleQuote: false,
	trailingComma: 'all',
	bracketSpacing: true,
	jsxBracketSameLine: false,
	arrowParens: 'always',
	proseWrap: 'always',
	htmlWhitespaceSensitivity: 'css',
	vueIndentScriptAndStyle: false,
	endOfLine: 'lf',
}
